defaults:
  - general: general
  - functions: Hartmann
  - acquisition: QBMGP
  - run: run_0
  - _self_
hydra:
  sweeper:
    params:
      functions: Higdon, Hartmann, Ishigami
      run: glob(*,exclude=run_0*)
      acquisition: SALHellingerMM, SALWassersteinMM, SALKLMM

      