defaults:
  - general: general
  - functions: Hartmann
  - acquisition: QBMGPAcquisitionFunction
  - _self_
hydra:
  sweeper:
    params:
      functions: Gramacy1d, Gramacy2d, Higdon, Hartmann, Branin
      acquisition: glob(*)