defaults:
  - general: general
  - functions: Hartmann
  - acquisition: QBMGP
  - _self_
hydra:
  sweeper:
    params:
      functions: Ishigami,Gramacy1d, Higdon, Hartmann, Branin
      acquisition: glob(*)