defaults:
  - general: general
  - functions: Hartmann
  - acquisition: QBMGP
  - type: part_bayesian
  - task: AL
  - run: run_0
  - _self_
  - override hydra/launcher: joblib

hydra:
  launcher:
    n_jobs: 1
  sweeper:
    params:
      functions:  Ishigami
      run: run_1, run_2, run_3, run_4, run_5
      acquisition: BQBC, QBMGP, BALM, RANDOM, SALHellingerMM, SALWassersteinMM, BALDKLMM
      type: part_bayesian
      task: AL

      