defaults:
  - general: general
  - functions: Hartmann
  - acquisition: QBMGP
  - type: part_bayesian
  - task: AL
  - run: run_0
  - _self_
  - override hydra/launcher: joblib

hydra:
  launcher:
    n_jobs: 4
  sweeper:
    params:
      functions:  BraninBO, Hartmann3dBO, Hartmann4dBO, Hartmann6dBO, Rosenbrock2dBO, Rosenbrock4dBO
      run: run_1, run_2, run_3, run_4, run_5, run_6, run_7, run_8, run_9, run_10
      acquisition: ScoreBOHellinger, ScoreBOWasserstein
      type: bayesian
      task: BO

      